### ISSUE TITLE
nyc doesn't show reports after running unit tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-googleapis-common#105]
So, the code coverage on this module is not very good.  I wanted to run `npm test`, and take a look at the lines that need more coverage.  Alas - no `nyc` code coverage report shows up!  I have no idea why.

**Comment by bcoe** [comment]
what version of Node.js are you running, and which test command are you running?

I'm on `v11.12.0` running `npm test`, and seem to get appropriate results:

<img width="840" alt="Screen Shot 2019-03-23 at 5 26 39 PM" src="https://user-images.githubusercontent.com/194609/54873307-d672fc00-4d90-11e9-9a25-f140443f9bad.png">

**Comment by JustinBeckwith** [comment]
Oooo - adventure and intrigue!  I am also using `v11.12.0`, running on OSX. 

```
nodejs-googleapis-common (master) $ npm test

> googleapis-common@0.7.2 pretest /Users/beckwith/Code/nodejs-googleapis-common
> npm run compile


> googleapis-common@0.7.2 compile /Users/beckwith/Code/nodejs-googleapis-common
> tsc -p .


> googleapis-common@0.7.2 test /Users/beckwith/Code/nodejs-googleapis-common
> nyc mocha build/test



  createAPIRequest
    instantiation
      ✓ should create a valid API request
      ✓ should include directives in the user agent
    mock stream
      ✓ should pass all chunks

  isbrowser
    ✓ should not detect browser


  4 passing (51ms)


> googleapis-common@0.7.2 posttest /Users/beckwith/Code/nodejs-googleapis-common
> npm run check


> googleapis-common@0.7.2 check /Users/beckwith/Code/nodejs-googleapis-common
> gts check

nodejs-googleapis-common (master) $ 
```

**Comment by JustinBeckwith** [comment]
This is going to be covered more generally by https://github.com/googleapis/google-cloud-node/issues/2914
