### ISSUE TITLE
Conflict with google-auth-library

### ISSUE THREAD

**Issue by hugocbpassos** [googleapis/nodejs-googleapis-common#129]
#3 is happening again when using `google-auth-library` 4.0.0. I'm if sorry this repo is not the proper one, I'm not sure whether I should open an issue here or at `google-auth-library`'s repo.

**Comment by bcoe** [comment]
@hugocbpassos it looks like both `googleapis`, and `@googleapis-common` are relying on `google-auth-library@4.0.0`, are you still running into issue? if so, any chance you could share a minimal reproduction?

**Comment by hugocbpassos** [comment]
@bcoe I'm really sorry, I didn't expressed myself properly. This issue is not exactly like #3. In my project, I have the dependencies `"googleapis": "^39.2.0"` and `"google-auth-library": "^3.1.2"`. If I update `google-auth-library` to 4.0.0, two different `OAuth2Client` conflict.

```typescript
import {auth, OAuth2Client} from 'google-auth-library';

import {androidpublisher_v3} from "googleapis";
import Androidpublisher = androidpublisher_v3.Androidpublisher;

...

async createAndroidpublisher(): Promise<Androidpublisher> {
  return new Androidpublisher({
    // Error message: Type 'OAuth2Client' is not assignable to type  'string | OAuth2Client | undefined'
    auth: await this.createAuthClient()
  });
}

createAuthClient(): Promise<OAuth2Client> {
  return auth.getClient({
    scopes: 'https://www.googleapis.com/auth/androidpublisher',
    credentials: {
      client_email: ServiceAccount.client_email,
      private_key: ServiceAccount.private_key
    }
  });
}
```

So `createAuthClient` returns a `OAuth2Client`, but `Androidpublisher`'s `auth` expects another `OAuth2Client`.

**Comment by bcoe** [comment]
@hugocbpassos is the issue you're getting a TypeScript compilation error, I'm trying to reproduce the issue locally without luck, I have the following code:

```js
import {auth, OAuth2Client} from 'google-auth-library';

import {androidpublisher_v3} from 'googleapis';
import Androidpublisher = androidpublisher_v3.Androidpublisher;

async function createAndroidpublisher(): Promise<Androidpublisher> {
  return new Androidpublisher({
    // Error message: Type 'OAuth2Client' is not assignable to type 'string | OAuth2Client | undefined'
    auth: await this.createAuthClient()
  });
};

function createAuthClient(): Promise<OAuth2Client> {
  return auth.getClient({
    scopes: 'https://www.googleapis.com/auth/androidpublisher',
    credentials: {
      client_email: 'bob@example.com',
      private_key: 'privatekey'
    }
  });
};
```

Perhaps try explicitly `npm i googleapis@40.0.0`? I might also recommend removing your `package-lock.json` and `node_modules` folder, and testing with a fresh install.

**Comment by JustinBeckwith** [comment]
Yeah - the versions of googleapis and google-auth-library need to line up.  For google-auth-library@4.0.0 you need googleapis@40.0.0 or up.  Hope this helps!
