### ISSUE TITLE
Derived Types Not Assignable to OAuth2Client

### ISSUE THREAD

**Issue by scottdewald** [googleapis/nodejs-googleapis-common#145]
The below code was working before I upgraded my packages, but now it will not compile. `getClient()` returns a `Promise<Compute | JWT | UserRefreshClient>` and each of those types derive from `OAuth2Client`, but the result is not assignable. 

```
let googleAuth: OAuth2Client;       // lazily initialize

async function getGoogleAuthClient(): Promise<OAuth2Client> {
    if (!googleAuth) {
        googleAuth = await google.auth.getClient({
            credentials: credentialsFile,
            scopes: ['https://www.googleapis.com/auth/androidpublisher']
        });
    }

    return googleAuth;
}
```

Here is the error I am getting:
```
  Type 'Compute' is not assignable to type 'OAuth2Client'.
    Types have separate declarations of a private property 'redirectUri'.
>>>         googleAuth = await google.auth.getClient({

```

I am using Typescript 3.4.5 with the following packages:
```
"dependencies": {
    "@google-cloud/pubsub": "^0.29.1",
    "aws-sdk": "^2.382.0",
    "elasticsearch": "^15.2.0",
    "firebase-admin": "^8.1.0",
    "firebase-functions": "^3.0.1",
    "googleapis": "^40.0.0",
    "googleapis-common": "^2.0.2",
    "http-aws-es": "^6.0.0",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.7"
  },
```

**Comment by JustinBeckwith** [comment]
Greetings!  This generally happens when there's a mismatch of the version of `google-auth-library` installed.  I *think* we should have these all cleared up.  Could we trouble you to update the latest version of your deps, and try this again?

**Comment by scottdewald** [comment]
@JustinBeckwith Updated to new deps and it is working now. Thanks!
