### ISSUE TITLE
loosen the typing on GlobalOptions.auth

### ISSUE THREAD

**Issue by proppy** [googleapis/nodejs-googleapis-common#175]
**Is your feature request related to a problem? Please describe.**

Currently, the library allows passing a `google.auth.GoogleAuth` as a parameters to api bindings builder functions when using JS:
```
const auth = new google.auth.GoogleAuth({
  scopes: ['https://www.googleapis.com/auth/homegraph']
});
const homegraph = google.homegraph({
  version: 'v1',
  auth: auth,
});
```
But the same thing will actually fails when using typescript because the api builder actually expect an [`OAuth2Client`](https://github.com/googleapis/nodejs-googleapis-common/blob/218ead79a5db0ff6bc24e46306afe6c4ce43255b/src/api.ts#L43):
```
t.ts:9:3 - error TS2322: Type 'GoogleAuth' is not assignable to type 'string | OAuth2Client'.
  Type 'GoogleAuth' is missing the following properties from type 'OAuth2Client': certificateCache, certificateExpiry, certificateCacheFormat, refreshTokenPromises, and 42 more.

9   auth: auth,
    ~~~~

  node_modules/googleapis-common/build/src/api.d.ts:24:5
    24     auth?: OAuth2Client | string;
           ~~~~
    The expected type comes from property 'auth' which is declared here on type 'Options'


Found 1 error.
```

 **Describe the solution you'd like**

It'd be nice to be able to pass any [`AuthClient`](https://github.com/googleapis/google-auth-library-nodejs/blob/d7547714af0bb405b8230cee189419efd4a75f0c/src/auth/authclient.ts#L27) to the api builder as the only assumption seems to be that it implement [`request`](https://github.com/googleapis/nodejs-googleapis-common/blob/218ead79a5db0ff6bc24e46306afe6c4ce43255b/src/apirequest.ts#L294).

 **Describe alternatives you've considered**

Calling `.getClient()` and passing to result to the api builder cool work, but this prove to be inconvenient since it's async and *top-level* await in not there yet.

**Comment by proppy** [comment]
@bcoe I'm trying to make `GlobalOptions` accept `GoogleAuth` as its `auth` attribute.

Exposing `AuthClient` seemed like the natural thing to do, since `GoogleAuth` seems to satisfy its contact, but I'm also happy to use an union type `OAuth2Client | GoogleAuth` if you think that's more appropriate (and it won't require exporting anything new in the auth library).

**Comment by bcoe** [comment]
@proppy sorry for dropping this on the floor for so long, I think I would prefer the second approach `OAuth2Client | GoogleAuth`; seems like it's slightly less likely to break folks who are perhaps calling `instanceof` (as an example).

If you want to rebase your PR, I'll happily land it ASAP.
