### ISSUE TITLE
Proposal: replace qs dependency with query-string

### ISSUE THREAD

**Issue by rapzo** [googleapis/nodejs-googleapis-common#206]
While there's nothing wrong with the `qs` dependency, it does a lot more than what is needed here and there are pleasant alternatives for simple purposes, such as `query-string`.
The `qs` module also requires the `@types/qs` dependency for typescript support where `query-string` does not (has its own).

It is already implemented in #205 

The PR also comes with the fix for mocha's deprecation warning for using `mocha.opts` file, which would prevent updating to the next major. It's in a separate commit so it can be cherrypicked or even separated to another PR.

Thank you.

**Comment by JustinBeckwith** [comment]
Greetings!  We're pretty happy with the `qs` module right now :) If there are specific things you need here, let us know and we'll consider it!
