### ISSUE TITLE
Differing versions of google-auth-library

### ISSUE THREAD

**Issue by SebastianEdwards** [googleapis/nodejs-googleapis-common#3]
Differing versions of `google-auth-library` between `googleapis` (1.6.0) and `googleapis-common` (1.4.0) leads to TypeScript error.

```
Argument of type '{ auth: OAuth2Client; }' is not assignable to parameter of type 'GlobalOptions'.
  Types of property 'auth' are incompatible.
    Type 'OAuth2Client' is not assignable to type 'string | OAuth2Client'.
      Type 'import("/Users/sebastianedwards/Code/uprise/node_modules/google-auth-library/build/src/auth/oauth2client").OAuth2Client' is not assignable to type 'import("/Users/sebastianedwards/Code/uprise/node_modules/googleapis-common/node_modules/google-auth-library/build/src/auth/oauth2client").OAuth2Client'.
        Types have separate declarations of a private property 'redirectUri'.
```

**Comment by SebastianEdwards** [comment]
Sorry, I should have clarified - this issue _is_ the result of upgrading to `googleapis@33.0.0`.

While `googleapis@33.0.0` uses `google-auth-library@1.6.0` it now also depends on this library which in turn depends on `google-auth-library@1.4.0`. The differences between these two versions causes the incompatibility error.

**Comment by JustinBeckwith** [comment]
🤦‍♂️

**Comment by JustinBeckwith** [comment]
@SebastianEdwards I just cut a release with the fix - could you give this a try?

**Comment by SebastianEdwards** [comment]
Thanks @JustinBeckwith - the new release has solved the problem 👍

**Comment by Gullfaxi171** [comment]
Hi guys, looks like the issue came back

In my case:
* googleapis: 34.0.0
* google-auth-library: 1.6.1

```
TS2345: Argument of type 'import("C:/path/to/node_modules/googleapis/node_modules/google-auth-library/build/src/auth/oauth2client").OAuth2Client' is not assignable to parameter of type 'import("C:/path/to/node_modules/google-auth-library/build/src/auth/oauth2client").OAuth2Client'.
  Types have separate declarations of a private property 'redirectUri'.
```

**Comment by sauravhiremath** [comment]
Looks like the problem has surfaced again. And there is a major version diff -

--------------

`google-auth-library` --> `^3.0.0` (from `googleapis@39)

`google-auth-library` --> `^6.1.6` (latest `google-auth-library`)

--------------
Lowering the `google-auth-library` version to v3.0.0 solved the issue for now 👍🏽
