### ISSUE TITLE
option rootUrl is not replaced correctly

### ISSUE THREAD

**Issue by yitomok** [googleapis/nodejs-googleapis-common#351]
#### Environment details

  - OS: `any`
  - Node.js version: `^12`
  - npm version: `^6`
  - `googleapis-common` version: `4.4.3`

#### Steps to reproduce

```javascript
const { GoogleApis } = require('googleapis');

const google = new GoogleApis({
  rootUrl: 'https://googleapis-endpoint'
});

// gmail API is used for example, it should happen to others as they share createAPIRequest()
const gmail = google.gmail({
  version: 'v1',
  rootUrl: 'https://googleapis-gmail-endpoint'
});

// ERROR in replacing URL! (list API is used for example, should happen to all as described above)
gmail.users.history.list({
  userId: 'me'
};
```

https://github.com/googleapis/nodejs-googleapis-common/blob/8032a85f88dc1ffd1c0b5bc054386fc1ef24af9e/src/apirequest.ts#L176-L177

There are 2 issues in handling `rootUrl`:

1. It is not clear which `rootUrl` take precedence, global vs API specific, and take note of sub point iii
   1. **_Global_**, set by `new GoogleApis(...)` (`gmail.context.google._options.rootUrl === 'https://googleapis-endpoint'`)
   2. **_API specific_**, set by `google.gmail(...)` (`gmail.context._options.rootUrl === 'https://googleapis-gmail-endpoint'`)
   3. **Note**: in current implementation, **_Global_** setting has no effect whatsoever
2. The usage of `options.url.slice` above causes issue, from my example code:

```javascript
// FAIL! with actual url === 'https://googleapis-gmail-endpoint/l/v1/users/me/history'
gmail.users.history.list(...);
// slice function returns 'l/v1/users/me/history', since,
// 'https://googleapis-gmail-endpoint'.length === 33, i.e. 'https://gmail.googleapis.com/gmai' sliced
```

**Comment by bcoe** [comment]
@yitomok thank you for the bug report and patch 👍
