### ISSUE TITLE
GoogleApis options rootUrl is never used

### ISSUE THREAD

**Issue by yitomok** [googleapis/nodejs-googleapis-common#355]
#### Environment details

  - OS: `any`
  - Node.js version: `^12`
  - npm version: `^6`
  - `googleapis-common` version: `5.0.0`

#### Steps to reproduce

```javascript
const { GoogleApis } = require('googleapis');

const google = new GoogleApis({
  rootUrl: 'https://googleapis-endpoint'
});

// gmail API is used for example, it should happen to others as they share createAPIRequest()
const gmail = google.gmail('v1');

// Here it is still using default https://gmail.googleapis.com
gmail.users.history.list({ userId: 'me' });
```

**Comment by JustinBeckwith** [comment]
Greetings!  This isn't the way you set global options :) This is covered in the documentation here:
https://github.com/googleapis/google-api-nodejs-client#request-options

Does this currently work for you?

```js
const {google} = require('googleapis');
google.options({
  rootUrl: 'https://googleapis-endpoint',
});
```

**Comment by yitomok** [comment]
@JustinBeckwith The type definition [here](https://github.com/googleapis/google-api-nodejs-client/blob/fec087abcf3d994dd41c3ffa0a0c12b1f9f09dae/src/googleapis.ts#L43-L46
) says it can use `new`

nevertheless constructor is using the same `options()` [here](https://github.com/googleapis/google-api-nodejs-client/blob/fec087abcf3d994dd41c3ffa0a0c12b1f9f09dae/src/googleapis.ts#L64-L66), which is also not working.

The actual cause is not where the option is set, is how it is used, please see my PR #356

**Comment by JustinBeckwith** [comment]
Heh, the code was running ahead of the docs 😆   Thanks for the pointer!

**Comment by yitomok** [comment]
@JustinBeckwith any news?

**Comment by JustinBeckwith** [comment]
nope

**Comment by sofisl** [comment]
Closing this for now as we are not looking to support global setting of rootUrl. See [here](https://github.com/googleapis/nodejs-googleapis-common/blob/08a0118a48658cc3ec8d935362b3497f7777f01a/src/apirequest.ts#L169).
