### ISSUE TITLE
Failing due to unavailability of the "fs" package

### ISSUE THREAD

**Issue by ShaikhSuf** [googleapis/nodejs-googleapis-common#397]
#### Environment details

  - OS: Mac
  - Node.js version: 14.16.1
  - npm version: 7.13
  - `googleapis-common` version: 5.0.2

#### Steps to reproduce

  1. Install googleapis
  2. Run the application. 

The application throws the following error - 
error: Error: While trying to resolve module `fs` from file `/node_modules/googleapis-common/build/src/discovery.js`, the package `/node_modules/fs/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/fs/index.js`. Indeed, none of these files exist:

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!
Sufian.

**Comment by bcoe** [comment]
@ShaikhSuf `fs` is a built in Node.js module, so it seems odd that you'd bump into this issue.

Could you try:

`rm -rf node_modules`.
`rm package-lock.json`
`npm i`

And see if the problem persists?

**Comment by tmatsuo** [comment]
Let's close this. @ShaikhSuf Feel free to reopen if you still have the problem.
