### ISSUE TITLE
TypeScript issue: Type 'JSONClient | Compute' is not assignable to type 'JSONClient'

### ISSUE THREAD

**Issue by therealgilles** [googleapis/nodejs-googleapis-common#451]
I am trying to find the proper type for auth.getClient() in the code below:

```JS
let authClient: import('google-auth-library/build/src/auth/googleauth').JSONClient

const sheets = async (): Promise<sheets_v4.Sheets> => {
        try {
          if (!authClient) {
            // create a new JWT client using the key file downloaded from the Google Developer Console
            const auth = new google.auth.GoogleAuth({
              keyFile: ...,
              scopes: ...,
            })
            authClient = await auth.getClient()
          }

          return google.sheets({ version: 'v4', auth: authClient })
        } catch (err) {
          error(err)
          throw new Error(err)
        }
```

It seems it should be JSONClient but having to access the type through an import seems odd and then I get the following error:

```JS
Type 'JSONClient | Compute' is not assignable to type 'JSONClient'
```

Some advice/guidance would be appreciated.

**Comment by danielbankhead** [comment]
The appropriate type would be `AuthClient`:
```ts
import {AuthClient} from 'google-auth-library';
```

You can use the `ReturnType` utility as well:
```ts
type myType = ReturnType<GoogleAuth['getClient']>
```

Ref: https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype

**Comment by danielbankhead** [comment]
Thanks for the additional information - I now understand the error is on the `return google.sheets({ version: 'v4', auth: authClient })` line.

You can pass the `GoogleAuth` instance directly to `google.sheets`:
```ts
const auth = new google.auth.GoogleAuth({
  keyFile: ...,
  scopes: ...,
});

return google.sheets({version: 'v4', auth});
```

**Comment by therealgilles** [comment]
I used to pass the GoogleAuth object directly. I believe the example or documentation I looked up after upgrading to the latest version now says to use the auth client.

**Comment by therealgilles** [comment]
Thanks again for your quick response.

Here is a link: https://googleapis.dev/nodejs/googleapis/latest/sheets/index.html#service-account-credentials

```JS
const docs = require('@googleapis/docs')

const auth = new docs.auth.GoogleAuth({
  keyFilename: 'PATH_TO_SERVICE_ACCOUNT_KEY.json',
    // Scopes can be specified either as an array or as a single, space-delimited string.
  scopes: ['https://www.googleapis.com/auth/documents']
});
const authClient = await auth.getClient();

const client = await docs.docs({
    version: 'v1',
    auth: authClient
});
```

Here is another link: https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/jwt.js

```JS
 // Create a new JWT client using the key file downloaded from the Google Developer Console
  const auth = new google.auth.GoogleAuth({
    keyFile: path.join(__dirname, 'jwt.keys.json'),
    scopes: 'https://www.googleapis.com/auth/drive.readonly',
  });
  const client = await auth.getClient();

  // Obtain a new drive client, making sure you pass along the auth client
  const drive = google.drive({
    version: 'v2',
    auth: client,
  });
```

**Comment by danielbankhead** [comment]
Thanks, I can see how this is confusing - I synced with the team and I'll file an issue to update the documentation; I'm sure others would be confused as well. You can continue to directly pass `GoogleAuth` into the `auth` parameter.

Thanks for bringing this up!

**Comment by therealgilles** [comment]
@danielbankhead: Thank you for being so understanding and for contributing to my TypeScript education :)
